// Generated by gencpp from file horizon_slam/lidarFrame.msg
// DO NOT EDIT!


#ifndef HORIZON_SLAM_MESSAGE_LIDARFRAME_H
#define HORIZON_SLAM_MESSAGE_LIDARFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace horizon_slam
{
template <class ContainerAllocator>
struct lidarFrame_
{
  typedef lidarFrame_<ContainerAllocator> Type;

  lidarFrame_()
    : lidarCloud()
    , timestamp(0.0)
    , pose()
    , lessSharpIdx()
    , lessFlatIdx()  {
    }
  lidarFrame_(const ContainerAllocator& _alloc)
    : lidarCloud(_alloc)
    , timestamp(0.0)
    , pose(_alloc)
    , lessSharpIdx(_alloc)
    , lessFlatIdx(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _lidarCloud_type;
  _lidarCloud_type lidarCloud;

   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_type;
  _pose_type pose;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _lessSharpIdx_type;
  _lessSharpIdx_type lessSharpIdx;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _lessFlatIdx_type;
  _lessFlatIdx_type lessFlatIdx;





  typedef boost::shared_ptr< ::horizon_slam::lidarFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::horizon_slam::lidarFrame_<ContainerAllocator> const> ConstPtr;

}; // struct lidarFrame_

typedef ::horizon_slam::lidarFrame_<std::allocator<void> > lidarFrame;

typedef boost::shared_ptr< ::horizon_slam::lidarFrame > lidarFramePtr;
typedef boost::shared_ptr< ::horizon_slam::lidarFrame const> lidarFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::horizon_slam::lidarFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::horizon_slam::lidarFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace horizon_slam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'horizon_slam': ['/home/dji/horizon_ws/src/horizon_slam/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::horizon_slam::lidarFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::horizon_slam::lidarFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::horizon_slam::lidarFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::horizon_slam::lidarFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::horizon_slam::lidarFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::horizon_slam::lidarFrame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::horizon_slam::lidarFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6333994608c191713f6a347ac8f978b4";
  }

  static const char* value(const ::horizon_slam::lidarFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6333994608c19171ULL;
  static const uint64_t static_value2 = 0x3f6a347ac8f978b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::horizon_slam::lidarFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "horizon_slam/lidarFrame";
  }

  static const char* value(const ::horizon_slam::lidarFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::horizon_slam::lidarFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2 lidarCloud\n\
float64 timestamp\n\
float64[] pose\n\
uint32[] lessSharpIdx\n\
uint32[] lessFlatIdx\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
";
  }

  static const char* value(const ::horizon_slam::lidarFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::horizon_slam::lidarFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lidarCloud);
      stream.next(m.timestamp);
      stream.next(m.pose);
      stream.next(m.lessSharpIdx);
      stream.next(m.lessFlatIdx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lidarFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::horizon_slam::lidarFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::horizon_slam::lidarFrame_<ContainerAllocator>& v)
  {
    s << indent << "lidarCloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.lidarCloud);
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose[i]);
    }
    s << indent << "lessSharpIdx[]" << std::endl;
    for (size_t i = 0; i < v.lessSharpIdx.size(); ++i)
    {
      s << indent << "  lessSharpIdx[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.lessSharpIdx[i]);
    }
    s << indent << "lessFlatIdx[]" << std::endl;
    for (size_t i = 0; i < v.lessFlatIdx.size(); ++i)
    {
      s << indent << "  lessFlatIdx[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.lessFlatIdx[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HORIZON_SLAM_MESSAGE_LIDARFRAME_H
