// Generated by gencpp from file newmsg/X1Point.msg
// DO NOT EDIT!


#ifndef NEWMSG_MESSAGE_X1POINT_H
#define NEWMSG_MESSAGE_X1POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace newmsg
{
template <class ContainerAllocator>
struct X1Point_
{
  typedef X1Point_<ContainerAllocator> Type;

  X1Point_()
    : offset_time(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , reflectivity(0)
    , line(0)
    , labelId(0)  {
    }
  X1Point_(const ContainerAllocator& _alloc)
    : offset_time(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , reflectivity(0)
    , line(0)
    , labelId(0)  {
  (void)_alloc;
    }



   typedef uint32_t _offset_time_type;
  _offset_time_type offset_time;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef uint8_t _reflectivity_type;
  _reflectivity_type reflectivity;

   typedef uint8_t _line_type;
  _line_type line;

   typedef int32_t _labelId_type;
  _labelId_type labelId;





  typedef boost::shared_ptr< ::newmsg::X1Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::newmsg::X1Point_<ContainerAllocator> const> ConstPtr;

}; // struct X1Point_

typedef ::newmsg::X1Point_<std::allocator<void> > X1Point;

typedef boost::shared_ptr< ::newmsg::X1Point > X1PointPtr;
typedef boost::shared_ptr< ::newmsg::X1Point const> X1PointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::newmsg::X1Point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::newmsg::X1Point_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace newmsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'newmsg': ['/home/dji/iX1_0830_ws/src/newmsg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::newmsg::X1Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::newmsg::X1Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::newmsg::X1Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::newmsg::X1Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::newmsg::X1Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::newmsg::X1Point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::newmsg::X1Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba0cb88e90ab963f273a02f4822a7324";
  }

  static const char* value(const ::newmsg::X1Point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba0cb88e90ab963fULL;
  static const uint64_t static_value2 = 0x273a02f4822a7324ULL;
};

template<class ContainerAllocator>
struct DataType< ::newmsg::X1Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "newmsg/X1Point";
  }

  static const char* value(const ::newmsg::X1Point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::newmsg::X1Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Livox costom pointcloud format.\n"
"\n"
"uint32 offset_time      # offset time relative to the base time\n"
"float32 x               # X axis, unit:m\n"
"float32 y               # Y axis, unit:m\n"
"float32 z               # Z axis, unit:m\n"
"uint8 reflectivity      # reflectivity, 0~255\n"
"uint8 line              # laser number in lidar\n"
"int32 labelId           # point seg/track id\n"
"\n"
;
  }

  static const char* value(const ::newmsg::X1Point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::newmsg::X1Point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offset_time);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.reflectivity);
      stream.next(m.line);
      stream.next(m.labelId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct X1Point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::newmsg::X1Point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::newmsg::X1Point_<ContainerAllocator>& v)
  {
    s << indent << "offset_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.offset_time);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "reflectivity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reflectivity);
    s << indent << "line: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.line);
    s << indent << "labelId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.labelId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEWMSG_MESSAGE_X1POINT_H
